name: families validation

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2

      - run: npm install

      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schema.json
          INPUT_JSONS: ./families.json

      - name: Validate JSON part 2
        run: node validator.js
